 var rows=[    {A:"First Name :"   ,  B:`${currentData.Sname}`},
    {A:"Father' Name :"   ,  B:`${currentData.Fname}`},
    {A:"Mother's name :"   ,  B:`${currentData.Mname}`},
    {A:"Surname :"   ,  B:`${currentData.surName}`},
    {A:"Mother Tongue :"   ,  B:`${currentData.mt}`},
    {A:"Religion :"   ,  B:`${currentData.religion}`},
    {A:"Caste :"   ,  B:`${currentData.caste}`},
    {A:"Sub Caste :"   ,  B:`${currentData.Scaste}`},
    {A:"Date of Birth :"   ,  B:`${currentData.dob}`},
    {A:"Place Of Birth :"   ,  B:`${currentData.plb}`},
    {A:"City :"   ,  B:`${currentData.city}`},
    {A:"Tal :"   ,  B:`${currentData.tal}`},
    {A:"District :"   ,  B:`${currentData.dist}`},
    {A:"State :"   ,  B:`${currentData.state}`},
    {A:"Last School Attended :"   ,  B:`${currentData.Lschool}`},
    {A:"Father's Profession/Business :"   ,  B:`${currentData.Foccupation}`},
    {A:"Mother's Profession/Business :"   ,  B:`${currentData.Moccupation}`},
    {A:"Father's Annual Income :"   ,  B:`${currentData.Fincome}`},
    {A:"Mother's Annual Income :"   ,  B:`${currentData.Mincome}`},
    {A:"Residential Address :"   ,  B:`${currentData.Raddress}`},
    {A:"Residential Phone No :"   ,  B:`${currentData.Rno}`},
    {A:"Mobile No :"   ,  B:`${currentData.Mno}`},
    {A:"Office Address :"   ,  B:`${currentData.Oaddress}`},
    {A:"Office Phone No :"   ,  B:`${currentData.Ono}`},
    {A:"Original Birth Certificate Attached :",  B:`${currentData.bc}`},
    {A:"Original L/C and  Result Attached :"   ,  B:`${currentData.lc}`}
 ]
